//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Data
{
    using Saptra.WebApi.Models;
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SaptraEntities : DbContext
    {
        public SaptraEntities()
            : base("name=SaptraEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cCoordinacionesRegion> cCoordinacionesRegion { get; set; }
        public virtual DbSet<cCoordinacionesZona> cCoordinacionesZona { get; set; }
        public virtual DbSet<cEstatus> cEstatus { get; set; }
        public virtual DbSet<cPeriodos> cPeriodos { get; set; }
        public virtual DbSet<cTipoActividades> cTipoActividades { get; set; }
        public virtual DbSet<cTipoEstatus> cTipoEstatus { get; set; }
        public virtual DbSet<cTipoFiguras> cTipoFiguras { get; set; }
        public virtual DbSet<cTipoNotificaciones> cTipoNotificaciones { get; set; }
        public virtual DbSet<cTiposUsuario> cTiposUsuario { get; set; }
        public virtual DbSet<mLecturaCertificados> mLecturaCertificados { get; set; }
        public virtual DbSet<mCoordinacionRegionZonaUsuario> mCoordinacionRegionZonaUsuario { get; set; }
        public virtual DbSet<mCoordinacionZonaUsuario> mCoordinacionZonaUsuario { get; set; }
        public virtual DbSet<mEducandosCaptados> mEducandosCaptados { get; set; }
        public virtual DbSet<InaebaPreregistros> InaebaPreregistros { get; set; }
        public virtual DbSet<dDetallePlanSemanal> dDetallePlanSemanal { get; set; }
        public virtual DbSet<mCheckIn> mCheckIn { get; set; }
        public virtual DbSet<mPlanSemanal> mPlanSemanal { get; set; }
        public virtual DbSet<dModulos> dModulos { get; set; }
        public virtual DbSet<mBitacora> mBitacora { get; set; }
        public virtual DbSet<mMenuGrupo> mMenuGrupo { get; set; }
        public virtual DbSet<mPermisos> mPermisos { get; set; }
        public virtual DbSet<mRoles> mRoles { get; set; }
        public virtual DbSet<mNotificaciones> mNotificaciones { get; set; }
        public virtual DbSet<mResetPassword> mResetPassword { get; set; }
        public virtual DbSet<mUsuarios> mUsuarios { get; set; }
        public virtual DbSet<mSolicitudesVehiculo> mSolicitudesVehiculo { get; set; }
        public virtual DbSet<CertificadosProgramados> CertificadosProgramados { get; set; }
    }
}
