//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class CertificadosProgramados
    {
        public int CertificadosId { get; set; }
        public int mc_id { get; set; }
        public string mc_nombre { get; set; }
        public string mc_curp { get; set; }
        public string mc_foliocert { get; set; }
        public string st_desc { get; set; }
        public string mc_fconclusion { get; set; }
        public string rfc_figura { get; set; }
        public string mc_matrnu { get; set; }
    }
}
