//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class cTipoActividades
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cTipoActividades()
        {
            this.dDetallePlanSemanal = new HashSet<dDetallePlanSemanal>();
        }
    
        public int TipoActividadId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public int EstatusId { get; set; }
        public string NombreActividad { get; set; }
        public string DescripcionActividad { get; set; }
        public bool RequiereCheckIn { get; set; }
        public Nullable<bool> ActividadEspecial { get; set; }
        public string Mensaje { get; set; }
    
        public virtual cEstatus cEstatus { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dDetallePlanSemanal> dDetallePlanSemanal { get; set; }
    }
}
