//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class dModulos
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public dModulos()
        {
            this.mPermisos = new HashSet<mPermisos>();
        }
    
        public int ModuloId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> EstatusId { get; set; }
        public string NombreModulo { get; set; }
        public string UrlModulo { get; set; }
        public string IconModulo { get; set; }
        public Nullable<int> OrdenModulo { get; set; }
        public Nullable<int> MenuGrupoId { get; set; }
    
        public virtual cEstatus cEstatus { get; set; }
        public virtual mMenuGrupo mMenuGrupo { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mPermisos> mPermisos { get; set; }
    }
}
