//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InaebaPreregistros
    {
        public int PreregistroId { get; set; }
        public string ben_nom { get; set; }
        public string ben_app { get; set; }
        public string ben_apm { get; set; }
        public string ben_nacf { get; set; }
        public string ben_reg { get; set; }
        public Nullable<int> num_activ_saptra { get; set; }
    }
}
