//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mBitacora
    {
        public long Id { get; set; }
        public Nullable<System.DateTime> ExecuteDate { get; set; }
        public string Ip { get; set; }
        public string Username { get; set; }
        public string Reqtype { get; set; }
        public string Reqdata { get; set; }
        public string Controller { get; set; }
        public string Action { get; set; }
    }
}
