//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCheckIn
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mCheckIn()
        {
            this.mLecturaCertificados = new HashSet<mLecturaCertificados>();
        }
    
        public int CheckInId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public string Coordenadas { get; set; }
        public int DetallePlanId { get; set; }
        public string Incidencias { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mLecturaCertificados> mLecturaCertificados { get; set; }
        public virtual dDetallePlanSemanal dDetallePlanSemanal { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
