//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mCoordinacionRegionZonaUsuario
    {
        public int CoordinacionRegionZonaId { get; set; }
        public int CoordinacionRegionId { get; set; }
        public int CoordinacionZonaId { get; set; }
        public int UsuarioJefeRegionId { get; set; }
    
        public virtual cCoordinacionesRegion cCoordinacionesRegion { get; set; }
        public virtual cCoordinacionesZona cCoordinacionesZona { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
