//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mEducandosCaptados
    {
        public int EducandoCaptadoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int EntidadNacimientoId { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string ColoniaLocalidad { get; set; }
        public string DependenciaAliado { get; set; }
        public int NivelEducativoId { get; set; }
        public Nullable<int> TipoExamenId { get; set; }
        public string CurpEducando { get; set; }
        public int DetallePlanId { get; set; }
    
        public virtual dDetallePlanSemanal dDetallePlanSemanal { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
