//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mEducandosCaptados
    {
        public int EducandoCaptadoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public string ApellidoPaterno { get; set; }
        public string ApellidoMaterno { get; set; }
        public string Nombres { get; set; }
        public System.DateTime FechaNacimiento { get; set; }
        public int EntidadNacimientoId { get; set; }
        public string Calle { get; set; }
        public string Numero { get; set; }
        public string ColoniaLocalidad { get; set; }
        public string DependenciaAliado { get; set; }
        public int NivelEducativoId { get; set; }
        public Nullable<int> TipoExamenId { get; set; }
        public string CurpEducando { get; set; }
        public int DetallePlanId { get; set; }
    
        public virtual dDetallePlanSemanal dDetallePlanSemanal { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
