//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mLecturaCertificados
    {
        public int LecturaCertificadoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public string FolioCertificado { get; set; }
        public int EstatusId { get; set; }
        public int CheckInId { get; set; }
    
        public virtual cEstatus cEstatus { get; set; }
        public virtual mCheckIn mCheckIn { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
