//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mNotificaciones
    {
        public int NotificacionId { get; set; }
        public int EstatusId { get; set; }
        public int TipoNotificacionId { get; set; }
        public int PlanSemanalId { get; set; }
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> CoordinacionZonaUsuarioId { get; set; }
    
        public virtual cEstatus cEstatus { get; set; }
        public virtual cTipoNotificaciones cTipoNotificaciones { get; set; }
        public virtual mPlanSemanal mPlanSemanal { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
        public virtual mCoordinacionZonaUsuario mCoordinacionZonaUsuario { get; set; }
    }
}
