//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPermisos
    {
        public int ModuloId { get; set; }
        public int RolId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> EstatusId { get; set; }
        public Nullable<bool> LecturaPermiso { get; set; }
        public Nullable<bool> EscrituraPermiso { get; set; }
        public Nullable<bool> EdicionPermiso { get; set; }
        public Nullable<bool> ClonadoPermiso { get; set; }
        public Nullable<bool> BorradoPermiso { get; set; }
    
        public virtual cEstatus cEstatus { get; set; }
        public virtual dModulos dModulos { get; set; }
        public virtual mRoles mRoles { get; set; }
    }
}
