//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mPlanSemanal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mPlanSemanal()
        {
            this.dDetallePlanSemanal = new HashSet<dDetallePlanSemanal>();
            this.mNotificaciones = new HashSet<mNotificaciones>();
        }
    
        public int PlanSemanalId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public int EstatusId { get; set; }
        public string DescripcionPlaneacion { get; set; }
        public int PeriodoId { get; set; }
    
        public virtual cEstatus cEstatus { get; set; }
        public virtual cPeriodos cPeriodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dDetallePlanSemanal> dDetallePlanSemanal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mNotificaciones> mNotificaciones { get; set; }
        public virtual mUsuarios mUsuarios { get; set; }
    }
}
