//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mSolicitudesVehiculo
    {
        public int SolicitudVehiculoId { get; set; }
        public System.DateTime FechaCreacion { get; set; }
        public int UsuarioCreacionId { get; set; }
        public int VehiculoId { get; set; }
        public System.DateTime FechaUso { get; set; }
        public Nullable<int> SolicitudSipaeId { get; set; }
        public int DetallePlanId { get; set; }
        public string PlacaVehiculo { get; set; }
    
        public virtual mUsuarios mUsuarios { get; set; }
        public virtual dDetallePlanSemanal dDetallePlanSemanal { get; set; }
    }
}
