//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Saptra.WebApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class mUsuarios
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public mUsuarios()
        {
            this.cCoordinacionesRegion = new HashSet<cCoordinacionesRegion>();
            this.cCoordinacionesZona = new HashSet<cCoordinacionesZona>();
            this.cEstatus = new HashSet<cEstatus>();
            this.cPeriodos = new HashSet<cPeriodos>();
            this.cTipoActividades = new HashSet<cTipoActividades>();
            this.cTipoEstatus = new HashSet<cTipoEstatus>();
            this.cTipoFiguras = new HashSet<cTipoFiguras>();
            this.cTipoNotificaciones = new HashSet<cTipoNotificaciones>();
            this.cTiposUsuario = new HashSet<cTiposUsuario>();
            this.mLecturaCertificados = new HashSet<mLecturaCertificados>();
            this.mCoordinacionZonaUsuario = new HashSet<mCoordinacionZonaUsuario>();
            this.mCoordinacionZonaUsuario1 = new HashSet<mCoordinacionZonaUsuario>();
            this.mEducandosCaptados = new HashSet<mEducandosCaptados>();
            this.dDetallePlanSemanal = new HashSet<dDetallePlanSemanal>();
            this.mCheckIn = new HashSet<mCheckIn>();
            this.mPlanSemanal = new HashSet<mPlanSemanal>();
            this.mNotificaciones = new HashSet<mNotificaciones>();
            this.mSolicitudesVehiculo = new HashSet<mSolicitudesVehiculo>();
        }
    
        public int UsuarioId { get; set; }
        public Nullable<System.DateTime> FechaCreacion { get; set; }
        public Nullable<int> EstatusId { get; set; }
        public string LoginUsuario { get; set; }
        public string PasswordUsuario { get; set; }
        public string NombresUsuario { get; set; }
        public string ApellidosUsuario { get; set; }
        public int RolId { get; set; }
        public string ImagenUsuario { get; set; }
        public string EmailUsuario { get; set; }
        public Nullable<int> TipoFiguraId { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cCoordinacionesRegion> cCoordinacionesRegion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cCoordinacionesZona> cCoordinacionesZona { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cEstatus> cEstatus { get; set; }
        public virtual cEstatus cEstatus1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cPeriodos> cPeriodos { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTipoActividades> cTipoActividades { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTipoEstatus> cTipoEstatus { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTipoFiguras> cTipoFiguras { get; set; }
        public virtual cTipoFiguras cTipoFiguras1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTipoNotificaciones> cTipoNotificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<cTiposUsuario> cTiposUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mLecturaCertificados> mLecturaCertificados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mCoordinacionZonaUsuario> mCoordinacionZonaUsuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mCoordinacionZonaUsuario> mCoordinacionZonaUsuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mEducandosCaptados> mEducandosCaptados { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<dDetallePlanSemanal> dDetallePlanSemanal { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mCheckIn> mCheckIn { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mPlanSemanal> mPlanSemanal { get; set; }
        public virtual mRoles mRoles { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mNotificaciones> mNotificaciones { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<mSolicitudesVehiculo> mSolicitudesVehiculo { get; set; }
    }
}
